name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root-pass

      neo4j:
        image: neo4j:5.9.0
        ports:
          - 7474:7474
          - 7687:7687
        options: >-
          --env=NEO4J_AUTH=none

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for services to be healthy
      run: sleep 60

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
